# Generated by Django 3.1.7 on 2021-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210313_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('terrain', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='walks',
            field=models.ManyToManyField(blank=True, to='main_app.Walk'),
        ),
    ]
